### ISSUE TITLE
Bad output when text exceeds terminal size

### ISSUE THREAD

**Issue by Lonney** [PowerShell/Win32-OpenSSH#712]
**"OpenSSH for Windows" version**
0.0.12.0

**OS details**
Windows 10 Enterprise 2016 LTSB

**What is failing**
When connecting to a Windows sshd server from another Windows machine, if the output of a command would otherwise scroll past the bottom of the terminal Window, the output overwrites itself on the last line.

If the output would _also_ exceed the width of the terminal when this happens, the output echoes every character change on a new line instead of wrapping.

**Expected output**
*Short local command-prompt:*
https://cloud.githubusercontent.com/assets/4212320/25813773/bf2e12c6-3412-11e7-8790-57c93319d715.gif

*Short & narrow local command-prompt:*
https://cloud.githubusercontent.com/assets/4212320/25814900/ea830f7c-3416-11e7-8e79-23d394a904ed.gif

**Actual output**
*Short PuTTY SSH:*
https://cloud.githubusercontent.com/assets/4212320/25813783/c66a2886-3412-11e7-9226-3b81debd66a9.gif

*Short & narrow PuTTY SSH:*
https://cloud.githubusercontent.com/assets/4212320/25814927/08ef040c-3417-11e7-8ace-abe316225de9.gif

*Short Tera Term SSH:*
https://cloud.githubusercontent.com/assets/4212320/25813786/c8a38f20-3412-11e7-9dd2-73a95075624b.gif

*Short & narrow Tera Term SSH:*
https://cloud.githubusercontent.com/assets/4212320/25814908/f351b202-3416-11e7-9b19-26a1cab08d3f.gif

**Notes**
I've exaggerated the small size of windows above to demonstrate what can happen.
I've tested two different SSH clients to confirm it's not just PuTTY being strange.

**Comment by manojampalam** [comment]
Thanks @Lonney for the detailed report. Can you try toggling SSH_TERM_CONHOST_PARSER as detailed in 
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH?

@bagajjal do you have any input? I thought we fixed this.

**Comment by bagajjal** [comment]
@Lonney -
It seems to be issue with the putty and teraterm. I have tried same command in both the terms, both of them exited with an exception in conhost.exe.
All other commands that produce bigger output like "dir c:\Windows\system32" works fine..

**putty exception**
![image](https://cloud.githubusercontent.com/assets/23668037/25918319/de98f4dc-357f-11e7-840e-fe94246ae266.png)

**teraterm exception**
![image](https://cloud.githubusercontent.com/assets/23668037/25918384/14489556-3580-11e7-8c17-ec1ad2f9deb9.png)

**It worked on the Cygwin and windows openssh client terminal.**

With windows openssh client terminal, first do "set SSH_TERM_CONHOST_PARSER=0" then do the ssh.. This will disable the windows 10 conhost xterm parser.

**Cygwin output**
![image](https://cloud.githubusercontent.com/assets/23668037/25918424/36b7b752-3580-11e7-8f4d-aeccb434444b.png)

**OpenSSH windows client output (With set SSH_TERM_CONHOST_PARSER=0)**
![image](https://cloud.githubusercontent.com/assets/23668037/25918572/bc8e3108-3580-11e7-9b6d-f4414cc49bcb.png)

**Comment by bagajjal** [comment]
when using "windows openssh client" we have a pre-requisite that the terminal size should be atleast 90 columns or above.. please refer to the wiki https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

**Comment by Lonney** [comment]
@manojampalam, @bagajjal,
Thank you, setting a greater width fixes the wrapping issue even if the window is narrow.

However, I'm still seeing the last line overwrite itself.
Although now after a certain number of lines of output the screen it gets stuck there, with the scrollback buffer set to 9999 for both machines.
I tried this with and without setting SSH_TERM_CONHOST_PARSER=0 and it didn't seem to change anything.

**cmd.exe**
https://cloud.githubusercontent.com/assets/4212320/25944459/57ef7b1a-363b-11e7-83c0-c7e0218a4ab4.gif

**Comment by remittor** [comment]
Bugfix: https://github.com/PowerShell/openssh-portable/pull/137

**Comment by bagajjal** [comment]
@remittor - Thanks for your continuous efforts..
Were you able to reproduce this issue at your end with checked-in code? Can you please point the problematic code snippet related to this issue.. I have gone through your PR, it is mostly about refactoring and I couldn't find the problematic code that can cause this issue.

FYI, the existing code works perfectly fine for us on multiple machines...

**Comment by remittor** [comment]
For reproduce line scroll bug:
1) set window height to 5 symbols (use putty or bitvise)
2) connect to remote sshd-win32
3) type "ipconfig" or "quser"

Test OpenSSH **0.0.13.0** on Win2012R2 x64 (use **Bitvise**):
- **quser**: https://cloud.githubusercontent.com/assets/9350115/26026251/a01edcf2-3800-11e7-8888-33098d410b56.gif
- **ipconfig**: https://cloud.githubusercontent.com/assets/9350115/26026258/c1fc6452-3800-11e7-94f0-90e2622aad00.gif

**Comment by bagajjal** [comment]
@Lonney - As a workaround while doing the ssh using -T option..
ssh.exe <user@ip> -T cmd.exe

**Comment by bagajjal** [comment]
putty workaround ,  go to Connection > SSH > TTY > check "Don't allocate a pseudo terminal"
![image](https://cloud.githubusercontent.com/assets/23668037/26018834/0839722e-3726-11e7-8df5-5e33d3a7e45a.png)

**Comment by remittor** [comment]
OpenSSH **0.0.13.0** tests on Win2012R2 x64 (used Putty latest version).

With option "Don't allocate a pseudo terminal":
- **quser**: https://cloud.githubusercontent.com/assets/9350115/26031662/6ea9f7b8-3884-11e7-920e-483f644c1ee3.gif

Without option "Don't allocate a pseudo terminal":
- **quser**: https://cloud.githubusercontent.com/assets/9350115/26031720/321ca082-3886-11e7-8f1c-8d07f593458d.gif
- **ipconfig**: https://cloud.githubusercontent.com/assets/9350115/26031796/5b4efd62-3889-11e7-8759-0481e537737d.gif
- **ipconfig** (network brandwidth is 25 Kbps): https://cloud.githubusercontent.com/assets/9350115/26031821/f596ca1c-3889-11e7-906c-28f039ad394f.gif

--------
Test via **Bitvise** (default options):
- **ipconfig**: https://cloud.githubusercontent.com/assets/9350115/26036211/293fa0a2-38e2-11e7-96d5-30228fc72318.gif

---------
Test via **Bitvise** after merging https://github.com/PowerShell/openssh-portable/pull/137:
- **ipconfig**: https://cloud.githubusercontent.com/assets/9350115/26045432/dd95444c-3952-11e7-859f-181912ea015c.gif

**Comment by Lonney** [comment]
@bagajjal The ssh -T and PuTTY workarounds work fine for me, thank you.

**Comment by remittor** [comment]
@bagajjal 
> putty workaround , go to Connection > SSH > TTY > check "Don't allocate a pseudo terminal"

In this mode history navigate not work!
Also backspace button clear command prompt!

**Comment by Lonney** [comment]
@remittor Is command history navigation supposed to work when PTY isn't used?

**Comment by remittor** [comment]
@Lonney Answer there: https://github.com/PowerShell/Win32-OpenSSH/issues/724
OpenSSH-Win32 is equ IE5/IE6 (not observe standard).

**Comment by bagajjal** [comment]
This is not seen any more with v1.0.0.0.

**Comment by merlinthemagic** [comment]
Just wanted to report that i am still seeing this issue on v1.0.0.0 running on Microsoft Windows [Version 10.0.15063] connecting from BASH running under CentOS 7.
```
devOps@wcm112@WCM112 C:\Users\admin>mode con
Status for device CON:
----------------------
    Lines:          9999
    Columns:        128
    Keyboard rate:  31
    Keyboard delay: 1
    Code page:      437
```

The minute the terminal hits 9999 lines the last line is just rewritten again and again. 
Adding the "-T" option to ssh mitigates the issue, however since this option changes behavior of the terminal when connection to other SSH servers it is not a viable fix in an environment where you do not know to OS on the server side.

One additional note, when connecting with putty to a clean install on Windows 10 the connection fails with message: 
`Disconnected server protocol violation unexpected SSH2_MSG_UNIMPLEMENTED. `

The last issue can be solved by changing the Algo selection policy and may be unrelated, but i thought i would mention it.

**Comment by bagajjal** [comment]
@merlinthemagic - Please create a new issue.
Regarding "Disconnected server protocol violation unexpected SSH2_MSG_UNIMPLEMENTED.", please provide putty logs and sshd.log (with DEBUG3 enabled).
