### ISSUE TITLE
Requesting PreTest of Chocolatey Package

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/Win32-OpenSSH#763]
@bingbing8 - could you (and anyone else who would like to help) pre-test the chocolatey package for me?

If you are able to test on Win 7 and Win 10 that would be great - but I understand if you don't have time for both.

The updates to OpenSSHUtils.psm1 in this chocolatey package fix the problems in #758

I have it staged on a test feed.

To install:
````
choco install openssh -confirm -params '"/SSHServerFeature"' -source https://www.myget.org/F/chocotesting/api/v2/
````
Then examine permissions and proper operation of SSHD

To uninstall:
````
choco install openssh -confirm -params '"/SSHServerFeature /DeleteConfigAndServerKeys"'
````

**Comment by bingbing8** [comment]
@DarwinJS  my next PR includes -confirm support and Verb changes, which breaks your script. that is the reason I can not to test against this package. If you could share the file chocolateyinstall.ps1 or chocolateyuninstall.ps1 I may be able to update them to use the new cmdlet names and new parameters for testing

**Comment by carlivar** [comment]
I tried your package (thank you for doing this).

It failed. However I've been having trouble with the permissions fix script prior to your package, I think because I'm on PS 4.0. Anyway, here are the results, partial paste showing context of the error:

```
C:\Program Files\OpenSSH-Win32\ssh-keygen.exe: generating new host keys: RSA DSA ECDSA ED25519
Ok.

WARNING: The following private keys should be removed from the machine:
[SC] ChangeServiceConfig SUCCESS
Ensuring all ssh key and configuration files have correct permissions for all users

ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to
 Stop: At C:\Program Files\OpenSSH-Win32\OpenSSHUtils.psm1:20 char:50
+         if ($PSVersionTable.PSVersion.Major -gt 2)
+                                                  ~
Missing statement block after if ( condition ).


The install of openssh was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\openssh\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - openssh
```

**Comment by carlivar** [comment]
Forgot to mention, above is on Windows Server 2012 R2

**Comment by DarwinJS** [comment]
@carlivar - Apologies - some cruft did make it back into the package.  I have fixed it and retested from the test feed.

**Comment by DarwinJS** [comment]
@bingbing8 - if you haven't already, could you please increment the module version number so that it is easy to tell that the Chocolatey release has a new version than the 0.0.15.0 zips ?

**Comment by manojampalam** [comment]
@DarwinJS based on when we can settle on the utility script updates, we can make a decision accordingly - with our end goal being - GitHub release version and chocolatey version are in sync. 

If we are done with script updates today, we'll update 0.0.15.0 zipped payload (since the binaries haven't changed) with the new scripts and along with updated instructions on the wiki. If this process bleeds into next week, we can as well plan on scheduling a simultaneous release of 0.0.16.0 for both Zipped and Chocolatey versions.

**Comment by carlivar** [comment]
@DarwinJS It seems to have installed correctly now for me. However, I'm still not able to authenticate from a client successfully (though it gets part of the way, so it's not a firewall issue or such).

With your package I'm having a hard time troubleshooting because for some reason `C:\Program Files\OpenSSH-Win32\Logs` does not contain an sshd.log (it only has ssh-agent.log, which is empty). In my prior self-installations, I had a log here (where I wound up troubleshooting various permission errors for the most part).

**Comment by bagajjal** [comment]
@carlivar  can you check sshd_config has the loglevel set properly (LOGLEVEL DEBUG3)

**Comment by carlivar** [comment]
I found the problem. The Logs subdirectory did not have any permissions for the sshd service.

I now have an sshd.log after running: `icacls.exe Logs /grant sshd:F`

This may also need to be part of the choco install script?

**Comment by carlivar** [comment]
Hmm, looks like my troubles are still related to the permissions fix script at install time. Here's the excerpt from that. I thought it had worked, but does not appear so from the below. I replaced our domain and my username with FOO\my.username. I ran the choco installer logged in with my domain (Administrators group) user and from an Administrator powershell prompt. Should I be running it differently?

```
C:\Program Files\OpenSSH-Win32\ssh-keygen.exe: generating new host keys: RSA DSA ECDSA ED25519
Ok.

WARNING: The following private keys should be removed from the machine:
[SC] ChangeServiceConfig SUCCESS
Ensuring all ssh key and configuration files have correct permissions for all users

  [*] C:\Program Files\OpenSSH-Win32\sshd_config

inheritance is removed from C:\Program Files\OpenSSH-Win32\sshd_config.

'BUILTIN\Users' has no more access to C:\Program Files\OpenSSH-Win32\sshd_config.

'APPLICATION PACKAGE AUTHORITY\ALL APPLICATION PACKAGES' has no more access to C:\Program Files\OpenSSH-Win32\sshd_confi
g.

'NT SERVICE\sshd' now has Read access to C:\Program Files\OpenSSH-Win32\sshd_config.

      fixed permissions



  [*] C:\Program Files\OpenSSH-Win32\ssh_host_dsa_key

'NT AUTHORITY\SYSTEM' now owns C:\Program Files\OpenSSH-Win32\ssh_host_dsa_key.

'FOO\my.username' has no more access to C:\Program Files\OpenSSH-Win32\ssh_host_dsa_key.

'NT SERVICE\sshd' now has Read access to C:\Program Files\OpenSSH-Win32\ssh_host_dsa_key.

The security identifier is not allowed to be the owner of this object.
      fixed permissions



  [*] C:\Program Files\OpenSSH-Win32\ssh_host_dsa_key.pub

'NT AUTHORITY\SYSTEM' now owns C:\Program Files\OpenSSH-Win32\ssh_host_dsa_key.pub.

'FOO\my.username' now has Read access to C:\Program Files\OpenSSH-Win32\ssh_host_dsa_key.pub.

The security identifier is not allowed to be the owner of this object.
      fixed permissions



  [*] C:\Program Files\OpenSSH-Win32\ssh_host_ecdsa_key

'NT AUTHORITY\SYSTEM' now owns C:\Program Files\OpenSSH-Win32\ssh_host_ecdsa_key.

'FOO\my.username' has no more access to C:\Program Files\OpenSSH-Win32\ssh_host_ecdsa_key.

'NT SERVICE\sshd' now has Read access to C:\Program Files\OpenSSH-Win32\ssh_host_ecdsa_key.

The security identifier is not allowed to be the owner of this object.
      fixed permissions



  [*] C:\Program Files\OpenSSH-Win32\ssh_host_ecdsa_key.pub

'NT AUTHORITY\SYSTEM' now owns C:\Program Files\OpenSSH-Win32\ssh_host_ecdsa_key.pub.

'FOO\my.username' now has Read access to C:\Program Files\OpenSSH-Win32\ssh_host_ecdsa_key.pub.

The security identifier is not allowed to be the owner of this object.
      fixed permissions



  [*] C:\Program Files\OpenSSH-Win32\ssh_host_ed25519_key

'NT AUTHORITY\SYSTEM' now owns C:\Program Files\OpenSSH-Win32\ssh_host_ed25519_key.

'FOO\my.username' has no more access to C:\Program Files\OpenSSH-Win32\ssh_host_ed25519_key.

'NT SERVICE\sshd' now has Read access to C:\Program Files\OpenSSH-Win32\ssh_host_ed25519_key.

The security identifier is not allowed to be the owner of this object.
      fixed permissions



  [*] C:\Program Files\OpenSSH-Win32\ssh_host_ed25519_key.pub

'NT AUTHORITY\SYSTEM' now owns C:\Program Files\OpenSSH-Win32\ssh_host_ed25519_key.pub.

'FOO\my.username' now has Read access to C:\Program Files\OpenSSH-Win32\ssh_host_ed25519_key.pub.

The security identifier is not allowed to be the owner of this object.
      fixed permissions



  [*] C:\Program Files\OpenSSH-Win32\ssh_host_rsa_key

'NT AUTHORITY\SYSTEM' now owns C:\Program Files\OpenSSH-Win32\ssh_host_rsa_key.

'FOO\my.username' has no more access to C:\Program Files\OpenSSH-Win32\ssh_host_rsa_key.

'NT SERVICE\sshd' now has Read access to C:\Program Files\OpenSSH-Win32\ssh_host_rsa_key.

The security identifier is not allowed to be the owner of this object.
      fixed permissions



  [*] C:\Program Files\OpenSSH-Win32\ssh_host_rsa_key.pub

'NT AUTHORITY\SYSTEM' now owns C:\Program Files\OpenSSH-Win32\ssh_host_rsa_key.pub.

'FOO\my.username' now has Read access to C:\Program Files\OpenSSH-Win32\ssh_host_rsa_key.pub.

The security identifier is not allowed to be the owner of this object.
      fixed permissions



  [*] C:\Users\my.username\.ssh\authorized_keys

'NT SERVICE\sshd' now has Read access to C:\Users\my.username\.ssh\authorized_keys.

      fixed permissions



   Done.



Account: NT SERVICE\SSHD

Account SID: S-1-5-80-3847866527-469524349-687026318-516638107-1125189541

Export current Local Security Policy


The task has completed successfully.
See log %windir%\security\logs\scesrv.log for detail info.
NO ACTIONS REQUIRED! Account already in "Replace a process level token"

Done.

Account: NT SERVICE\SSHD

Account SID: S-1-5-80-3847866527-469524349-687026318-516638107-1125189541

Export current Local Security Policy


The task has completed successfully.
See log %windir%\security\logs\scesrv.log for detail info.
Modify Setting "Logon as a Service"

*S-1-5-80-3847866527-469524349-687026318-516638107-1125189541,Services_Logon_Group,*S-1-5-80-0,*S-1-5-80-2277354432-2697
620045-1656008878-1855416240-261295475,*S-1-5-82-1036420768-1044797643-1061213386-2937092688-4282445334,*S-1-5-82-271721
585-897601226-2024613209-625570482-296978595,*S-1-5-82-3006700770-424185619-1745488364-794895919-4004696415,*S-1-5-82-36
82073875-1643277370-2842298652-3532359455-2406259117,*S-1-5-82-3876422241-1344743610-1729199087-774402673-2621913236,*S-
1-5-82-4068219030-1673637257-3279585211-533386110-4122969689

Import new settings to Local Security Policy

Completed 6 percent (0/15)      Process Privilege Rights area
Completed 13 percent (1/15)     Process Privilege Rights area
Completed 20 percent (2/15)     Process Privilege Rights area
Completed 26 percent (3/15)     Process Privilege Rights area
Completed 33 percent (4/15)     Process Privilege Rights area
Completed 40 percent (5/15)     Process Privilege Rights area
Completed 46 percent (6/15)     Process Privilege Rights area
Completed 53 percent (7/15)     Process Privilege Rights area
Completed 60 percent (8/15)     Process Privilege Rights area
Completed 66 percent (9/15)     Process Privilege Rights area
Completed 73 percent (10/15)    Process Privilege Rights area
Completed 100 percent (15/15)   Process Privilege Rights area

The task has completed successfully.
See log %windir%\security\logs\scesrv.log for detail info.
Done.
```

**Comment by carlivar** [comment]
I see the problem. Probably unrelated to the choco package itself. `OpenSSHUtils.psm1` doesn't set permissions correctly. Here's what happens when run interactively, below. I will try to figure out how to get around that (pretty new to powershell). Also this isn't related to the choco package itself so will try to find an appropriate Issue for this problem, but want to close the loop here.

```PS C:\Program Files\OpenSSH-Win32> .\FixHostFilePermissions.ps1
  [*] C:\Program Files\OpenSSH-Win32\sshd_config
      looks good

  [*] C:\Program Files\OpenSSH-Win32\ssh_host_dsa_key
WARNING: Current owner: 'FOO\my.username'. 'NT AUTHORITY\SYSTEM' should own C:\Program
Files\OpenSSH-Win32\ssh_host_dsa_key.
Shall I set the file owner? [Yes] Y; [No] N (default is "Y"): Y
'NT AUTHORITY\SYSTEM' now owns C:\Program Files\OpenSSH-Win32\ssh_host_dsa_key.
WARNING: 'OPS\carl.johnson' should not have access to 'C:\Program Files\OpenSSH-Win32\ssh_host_dsa_key'.
Shall I remove this access? [Yes] Y; [No] N (default is "Y"): Y
'FOO\my.username' has no more access to C:\Program Files\OpenSSH-Win32\ssh_host_dsa_key.
WARNING: 'NT SERVICE\sshd' needs Read access to C:\Program Files\OpenSSH-Win32\ssh_host_dsa_key'.
Shall I make the above change? [Yes] Y; [No] N (default is "Y"): Y
'NT SERVICE\sshd' now has Read access to C:\Program Files\OpenSSH-Win32\ssh_host_dsa_key.
Set-Acl : The security identifier is not allowed to be the owner of this object.
At C:\Program Files\OpenSSH-Win32\OpenSSHUtils.psm1:459 char:9
+         Set-Acl -Path $FilePath -AclObject $acl
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (C:\Program File...sh_host_dsa_key:String) [Set-Acl], InvalidOperation
   Exception
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.SetAclCommand

      fixed permissions
```

**Comment by DarwinJS** [comment]
Thanks for all the help on this.
