### ISSUE TITLE
ssh-add claims id_rsa permissions to be too open

### ISSUE THREAD

**Issue by gildas** [PowerShell/Win32-OpenSSH#898]
Just tried:

```ssh
ssh-add
```

And it printed an error: Permissions for '....\id_rsa' are too open.

Although:

```
Repair-UserKeyPermission ~/me/.ssh/id_rsa
```

claims both the private and public key files "look good".

**"OpenSSH for Windows" version**
0.0.20.0
 
**Server OperatingSystem**
Windows 10 Enterprise

**Client OperatingSystem**
Windows 10 Enterprise

**Comment by bagajjal** [comment]
Please copy the screenshot output of repair user key permissions and the output of 

icacls id_rsa

**Comment by bagajjal** [comment]
Any update on this?

**Comment by gildas** [comment]
Sorry for the delay, here we go:

```posh
PS > ssh-add
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'C:\\Users\\me/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
```

And icacls:

```posh
PS > icacls C:\Users\gildas.cherruel\.ssh\id_rsa
C:\Users\me\.ssh\id_rsa MYDOMAIN\me:(F)

Successfully processed 1 files; Failed processing 0 files

PS > icacls C:\Users\gildas.cherruel\.ssh\id_rsa.pub
C:\Users\me\.ssh\id_rsa.pub NT AUTHORITY\SYSTEM:(I)(F)
                                         BUILTIN\Administrators:(I)(F)
                                         MYDOMAIN\me:(I)(F)

Successfully processed 1 files; Failed processing 0 files
```

And the results of FixUserFilePermission:
```
[2075] # FixUserFilePermissions.ps1
  [*] ~\.ssh\config
      looks good

  [*] C:\Users\me\.ssh\id_rsa
      looks good

  [*] C:\Users\me\.ssh\id_rsa.pub
      looks good

   Done.
```

**Comment by gildas** [comment]
Any update on this?

**Comment by bingbing8** [comment]
@gildas I don't repro this on 0.0.21.0. Can you try on 0.0.21.0? did you run ssh-add under user context of MYDOMAIN\me or any other context?
The other thing we saw before is that gildas.cherruel may have different sid from MYDOMAIN\me in some special situation. for example, after you migrate from a domain to a different domain. If this repro on 0.0.21.0. can you create a different user, login as that user, recreate the private key for that user, and try ssh-add under that user again?

**Comment by gildas** [comment]
Ok, obviously, I am not good at pattern matching..... MYDOMAIN\me was a feeble attempt to hide my true account name... duh.
It is all the same: gildas.cherruel is actually MYDOMAIN\me.
Sorry for the confusion.

I used it in an Administrator PowerShell, if that makes any difference?

Let me try on 0.0.21.0

**Comment by gildas** [comment]
Just upgraded to 0.0.21.0. Same problem.

**Comment by bingbing8** [comment]
@gildas, What is the file owner of the key files?
Can you create a different user, login as that user, recreate the private key for that user, and try ssh-add under that user again?

**Comment by JW0914** [comment]
More likely than not, _Administrators_ or _System_ is the owner of _%UserProfile%\\.ssh_, as one or the other is the default owner of _%UserProfile%_.

- The easiest way to prevent permissions errors, as well as to ensure only the correct users have access is to disable inheritance on _%UserProfile\\.ssh_, as well as every other directory or file contained within.
   - For example, _%UserProfile\\.ssh\\config_ should only be accessible by the user and no one else, yet it will be created with access permissions granted to _System_ and the _Administrators_ group if permissions are inherited from _%UserProfile\\.ssh_

**Comment by JW0914** [comment]
More likely than not, _Administrators_ or _System_ is the owner of _%UserProfile%\\.ssh\\id_rsa_, as one or the other is the default owner of _%UserProfile%_.

- The easiest way to prevent permissions errors, as well as to ensure only the correct users have access, is to disable inheritance on _%UserProfile%\\.ssh_, as well as every other directory or file contained within, ensuring the user is the owner of _%UserProfile%\\.ssh_ and all files/directories contained within.
   - For example, _%UserProfile%\\.ssh\\config_ should only be accessible by the user and no one else, yet it will be created with access permissions granted to _System_ and the _Administrators_ group if permissions are inherited from _%UserProfile%\\.ssh_
   - This will become even more problematic should a user choose to use variables in _%UserProfile%\\.ssh\\config_, as those variables will have to coincide to nested folders within _%UserProfile%\\.ssh_

**Comment by gildas** [comment]
@bingbing8 , the file owner is my domain user.
@JW0914 , my user is the sole owner, reader, etc, of the id_rsa file. As well as ~/.ssh ~/ssh/authorized_key, and all the files in ~/.ssh.

**Comment by gildas** [comment]
If I create a local user, add a key and set permissions properly, that local user can use `ssh-add` without any issue.

**Comment by JW0914** [comment]
@gildas It would seem this is specific to domain user accounts, especially with your latter reply, as I can't replicate with a local user either.  I have no experience with domain accounts, so someone else that does will need to chime in.

**Comment by bingbing8** [comment]
@gildas, the challenge for us is that ssh-add does not print out the debug info. I compiled a private ssh-add.exe for you. Can you replace the ssh-add.exe. It should provide you something like below and tell what permission is voilate the check. 
ssh-add.exe c:\Users\me\.ssh\id_rsa
debug3: Bad permissions. Try removing permissions for user: S-1-5-21-1418920174-3016791129-3224140898-1014 on file c:\\Users\\me\\.ssh\\id_rsa.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'c:\\Users\\yawang\\.ssh\\id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.[
[ssh-add64.zip](https://github.com/PowerShell/Win32-OpenSSH/files/1432516/ssh-add64.zip)
](url)

**Comment by bingbing8** [comment]
@gildas, my guess is that there may have two different sids map to the same MYDOMAIN\me in some special domain situation. for example, after you migrate from a domain to a different domain. 

The current challenge is that ssh-add does not print out the debug info. I compiled a private ssh-add.exe for you to print our more details about what is violating the check. Can you replace the ssh-add.exe and give a try? 

```ssh-add.exe 'c:\Users\me\.ssh\id_rsa```
debug3: Current user sid: S-1-5-21-2127521184-1604012920-1887927527-1195773
debug3: Bad owner (S-1-5-21-1412890174-3016792229-3224140898-1014) on c:\\Users\\me\\.ssh\\id_rsa
debug3: Expected valid owners: administrators, local system, or S-1-5-21-2127521184-1604012920-1887927527-1195773
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'c:\\Users\\me\\.ssh\\id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.

```ssh-add.exe c:\Users\me\.ssh\id_rsa```
debug3: Current user sid: S-1-5-21-2127521184-1604012920-1887927527-1195773
debug3: Bad permissions. Try removing permissions for user: S-1-5-21-1412890174-3016792229-3224140898-1014 on file c:\\Users\\me\\.ssh\\id_rsa.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'c:\\Users\\me\\.ssh\\id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.

[ssh-add64.zip](https://github.com/PowerShell/Win32-OpenSSH/files/1432821/ssh-add64.zip)

**Comment by gildas** [comment]
@bingbing8 , thanks a lot!

I ran it and got this:

```posh
[2177] # .\ssh-add.exe C:\Users\gildas.cherruel\.ssh\id_rsa
debug3: Current user sid: S-1-5-21-2037646214-965435356-1153635105-118596
debug3: Bad owner (S-1-5-21-3334980730-4293530145-2415107754-7617) on C:\\Users\\gildas.cherruel\\.ssh\\id_rsa
debug3: Expected valid owners: administrators, local system, or S-1-5-21-2037646214-965435356-1153635105-118596
```

Interestingly, in the file property dialog, the owner (`7617`) resolves as my domain user.
So, I went to the Change dialog box and re-applied the owner as my domain user.

This time I got:
```posh
debug3: Current user sid: S-1-5-21-2037646214-965435356-1153635105-118596
debug3: Bad permissions. Try removing permissions for user: S-1-5-21-3334980730-4293530145-2415107754-7617 on file C:\\Users\\gildas.cherruel\\.ssh\\id_rsa.
```

Seems like, I get to become the proper owner this time, though, this is still me...
In the File Security dialog box, the owner still has `7617` SID (I can see it getting resolved).


```posh
[2180] # icacls C:\Users\gildas.cherruel\.ssh\id_rsa
C:\Users\gildas.cherruel\.ssh\id_rsa CAMELOT\gildas.cherruel:(RX)
```

Security was:
```posh
[2179] # icacls C:\Users\gildas.cherruel\.ssh\id_rsa
C:\Users\gildas.cherruel\.ssh\id_rsa CAMELOT\gildas.cherruel:(F)
```

So, I reset the permissions, but from the security dialog box this time, checked the security:
```posh
[2180] # icacls C:\Users\gildas.cherruel\.ssh\id_rsa
C:\Users\gildas.cherruel\.ssh\id_rsa CAMELOT\gildas.cherruel:(RX)
```

Now ssh-add gives this:
```posh
debug3: Current user sid: S-1-5-21-2037646214-965435356-1153635105-118596
Enter passphrase for C:\Users\gildas.cherruel\.ssh\id_rsa:
Identity added: C:\Users\gildas.cherruel\.ssh\id_rsa (C:\Users\gildas.cherruel\.ssh\id_rsa)
debug3: Failed to open file:C:\\Users\\gildas.cherruel\\.ssh\\id_rsa-cert.pub error:2
debug3: Failed to open file:C:\\Users\\gildas.cherruel\\.ssh\\id_rsa-cert.pub.pub error:2
```

It still sees the current user as `118596` but does not complain anymore.

Mistery...

**Comment by gildas** [comment]
And to answer your guess. Yes, our domains were migrated recently by our global IT.

**Comment by bingbing8** [comment]
@gildas, from what you described above, after the migration of the domain, some meta data are not update to date. After you reset the owner and acl of CAMELOT\gildas.cherruel, the new and correct account `118596`  are used. That is why it does not complain any more. In the File Security dialog UI, the account CAMELOT\gildas.cherruel previous was `7617`, after you reset it has been changed to `118596`. 

If you run the following in powershell window, 
```powershell
$objSID = New-Object System.Security.Principal.SecurityIdentifier("S-1-5-21-2037646214-965435356-1153635105-118596")
$objUser2 = $objSID.Translate( [System.Security.Principal.NTAccount])
$objUser2.Value
```
You will see that this sid is resolved to CAMELOT\gildas.cherruel. you may be able to print out the account of 7617.

**Comment by heaths** [comment]
I get this when trying to follow instructions at https://devblogs.microsoft.com/powershell/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/ for the C:\PRogramData\ssh\ssh_host_ed25519_key and the service will not start. I've run the Repair-Ssh* cmdlets numerous times. I can add my personal keys but not the host keys.

**Comment by JW0914** [comment]
@heaths Please open new issues instead of replying to an issue that doesn't cover your issue.

Specific to your reply, please utilize the instructions in the [GitHub wiki](https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH) and _DO NOT_ install OpenSSH via Add Features _(why it still exists there is baffling)_.

**Comment by ValZapod** [comment]
You need to delete all inheritance and then give access only to yourself and open user level PowerShell. LOL.

**Comment by rapekas** [comment]
This may be fixed by recreation the directory `.ssh` under regular user.
